"""add_unique_contraint_to_hls_key

Revision ID: 182ac7e592ad
Revises: adfa81afb532
Create Date: 2025-07-24 09:16:08.468363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182ac7e592ad'
down_revision: Union[str, Sequence[str], None] = 'adfa81afb532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hls', ['hls_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hls', type_='unique')
    # ### end Alembic commands ###
