"""Update VideoMetaData model

Revision ID: 4e23b1ed4ed3
Revises: 789221d11ffe
Create Date: 2025-07-03 17:15:38.377921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e23b1ed4ed3'
down_revision: Union[str, Sequence[str], None] = '789221d11ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_metadata', sa.Column('key', sa.Text(), nullable=False))
    op.drop_constraint(op.f('video_metadata_url_key'), 'video_metadata', type_='unique')
    op.create_unique_constraint(None, 'video_metadata', ['key'])
    op.drop_column('video_metadata', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_metadata', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'video_metadata', type_='unique')
    op.create_unique_constraint(op.f('video_metadata_url_key'), 'video_metadata', ['url'], postgresql_nulls_not_distinct=False)
    op.drop_column('video_metadata', 'key')
    # ### end Alembic commands ###
