"""Add HLS table

Revision ID: adfa81afb532
Revises: 4e23b1ed4ed3
Create Date: 2025-07-23 08:00:29.789836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfa81afb532'
down_revision: Union[str, Sequence[str], None] = '4e23b1ed4ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_metadata_id', sa.Integer(), nullable=False),
    sa.Column('hls_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_metadata_id'], ['video_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hls')
    # ### end Alembic commands ###
